# PowerLine Format
format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#33658A)\
$cmd_duration\
[ ](fg:#33658A)\
"""

[username]
show_always = true
style_user = "fg:#FFFFFF bg:#9A348E"
style_root = "fg:#FFFFFF bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "fg:#FFFFFF bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#FFFFFF bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#FFFFFF bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[cmd_duration]
min_time = 500
disabled = false
style = "fg:#FFFFFF bg:#33658A"
format = '[ took $duration ]($style)'
